#!/usr/bin/env python3
"""
generate_cards.py
Scans the pokemon_cards/ folder and writes:
  cards.json      — for server-based use
  cards_data.js   — for direct file:// use (window.CARDS_DATA = {...})

Run from the same directory as index.html:
  python3 generate_cards.py
"""

import json
import re
import sys
from pathlib import Path

DOWNLOAD_DIR  = Path("pokemon_cards")
CARDS_JSON    = Path("cards.json")
CARDS_DATA_JS = Path("cards_data.js")

# Matches filenames like:
#   001_Alakazam_-_Base_Set_(BS)_#1.jpg          (plain number)
#   H008_Forretress_-_Skyridge_(SK)_#H8.jpg      (letter-prefixed holofoil)
#   SH003_Some_Card_-_Set_(XX)_#SH3.jpg
FNAME_RE = re.compile(
    r"^([A-Z]*)(\d+)_(.+)\.(jpg|jpeg|png|webp|gif)$", re.IGNORECASE
)


def scan() -> dict:
    if not DOWNLOAD_DIR.exists():
        print(f"  ✗  Folder not found: {DOWNLOAD_DIR.resolve()}")
        sys.exit(1)

    result = {}
    dirs = sorted(d for d in DOWNLOAD_DIR.iterdir() if d.is_dir() and not d.name.startswith("."))

    if not dirs:
        print(f"  ✗  No set folders found inside {DOWNLOAD_DIR}/")
        sys.exit(1)

    for d in dirs:
        cards = []
        for f in sorted(d.iterdir()):
            if not f.is_file() or f.name.startswith("."):
                continue
            m = FNAME_RE.match(f.name)
            if not m:
                continue
            letter  = m.group(1).upper()
            number  = int(m.group(2))
            rest    = m.group(3)
            card_name = rest.split(" - ")[0].replace("_", " ").strip()
            display_num = f"{letter}{number}" if letter else str(number)
            cards.append({
                "number":   display_num,
                "name":     card_name,
                "filename": f.name,
            })
        if cards:
            result[d.name] = cards
            print(f"  ✓  {d.name:<40} {len(cards):>4} cards")
        else:
            print(f"  –  {d.name:<40} (no recognised image files)")

    return result


def write(result: dict):
    payload = json.dumps(result, indent=2, ensure_ascii=False)

    CARDS_JSON.write_text(payload, encoding="utf-8")
    print(f"\n  ✓  {CARDS_JSON}  ({CARDS_JSON.stat().st_size // 1024} KB)")

    CARDS_DATA_JS.write_text(
        "/* Auto-generated by generate_cards.py — do not edit */\n"
        f"window.CARDS_DATA = {payload};\n",
        encoding="utf-8",
    )
    print(f"  ✓  {CARDS_DATA_JS}  ({CARDS_DATA_JS.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    print(f"Scanning {DOWNLOAD_DIR.resolve()} …\n")
    data = scan()
    total_sets  = len(data)
    total_cards = sum(len(v) for v in data.values())
    print(f"\n  {total_sets} sets  |  {total_cards} cards total")
    write(data)
    print("\nDone — open index.html in your browser.")
